// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package log

// Injectors from log_build.go:

func initializeLog() Loger {
	string2 := logLevel()
	loger := provideLog(string2)
	return loger
}
